# Project: ÏîÄ¿1
# Makefile created by Dev-C++ 5.6.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = PL0C_0.o
LINKOBJ  = PL0C_0.o
LIBS     = -L"E:/programs/Dev-Cpp/MinGW32/lib" -L"E:/programs/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -g3
INCS     = -I"E:/programs/Dev-Cpp/MinGW32/include" -I"E:/programs/Dev-Cpp/MinGW32/mingw32/include" -I"E:/programs/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"E:/programs/Dev-Cpp/MinGW32/include" -I"E:/programs/Dev-Cpp/MinGW32/mingw32/include" -I"E:/programs/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"E:/programs/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = PL0.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

PL0C_0.o: PL0C_0.C
	$(CPP) -c PL0C_0.C -o PL0C_0.o $(CXXFLAGS)
